# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cognify
subtitle: The Data Science Company
lang: de-AT
company:
  email: office@cognify.ai
  location: Judengasse 12, Top 3, Salzburg
  location-link: https://maps.google.com/maps?ll=47.799494,13.046457&amp;z=16&amp;t=m&amp;q=Judengasse%2012%205020%20Salzburg
  phone: tbd
  imprint:
    name: Cognify KG (Firma in Gründung)
    address:
      street: Judengasse 12, Top 3
      zip: 5020
      city: Salzburg
      country: Österreich
    firmensitz: Sitz Salzburg
    firmennummer: FN 477675p
    gerichtsstand: Landesgericht Salzburg
    dvr: Firma in Gründung
    uid: Firma in Gründung
description: >
  Unsere Mission: Ihre Wertschöpfung durch selbst-lernende,
  daten-getriebene Machine Learning Algorithmen zur vollen
  Entfaltung zu bringen!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

google:
  site-verification: q_gqTtu5Y0hW89Edt9yQAoVefhlrAcluCtcfGSNdiyM
  maps:
    embed-link: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2680.0690156938435!2d13.044267915841973!3d47.799497882625396!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4776906225dc4d13%3A0x4abedb1676fdbc27!2sJudengasse+12%2C+5020+Salzburg!5e0!3m2!1sde!2sat!4v1502520709512

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
